### ISSUE TITLE
Host API down

### ISSUE THREAD

**Issue by sonzaiekkusu** [Zacros-Team/ZacrosBot#10]
![Screenshot_2022-02-03-22-10-03-175_com android chrome](https://user-images.githubusercontent.com/61716582/152370208-cd33469d-ec44-4a92-99d3-1719687e7436.jpg)

**Comment by Azyansah** [comment]
Fixed

**Comment by sonzaiekkusu** [comment]
Kapan multi device?? 😂

**Comment by Azyansah** [comment]
> Kapan multi device?? 😂

kurang tau, males scan gw
